services:
  tucardex-db:
    image: mariadb:10.11
    container_name: tucardex-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-tucardex}
      MYSQL_USER: ${DB_USERNAME:-tucardex_user}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - tucardex_db_data:/var/lib/mysql
    networks:
      - internal

  tucardex-app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: tucardex-tucardex-app
    container_name: tucardex-app
    restart: unless-stopped
    volumes:
      - /opt/tucardex/app:/var/www/html
    networks:
      - internal
    depends_on:
      - tucardex-db

  tucardex-worker:
    image: tucardex-tucardex-app
    container_name: tucardex-worker
    restart: unless-stopped
    command: php /var/www/html/artisan queue:work --sleep=3 --tries=3 --timeout=90
    volumes:
      - /opt/tucardex/app:/var/www/html
    networks:
      - internal
    depends_on:
      - tucardex-db

  tucardex-web:
    image: nginx:alpine
    container_name: tucardex-web
    restart: unless-stopped
    volumes:
      - /opt/tucardex/app:/var/www/html:ro
      - /opt/tucardex/docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - internal
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tucardex.rule=Host(`tucardex.allia2.com.mx`)"
      - "traefik.http.routers.tucardex.entrypoints=web,websecure"
      - "traefik.http.routers.tucardex.tls=true"
      - "traefik.http.routers.tucardex.tls.certresolver=mytlschallenge"
      - "traefik.http.services.tucardex.loadbalancer.server.port=80"
      - "traefik.docker.network=n8n_default"
    depends_on:
      - tucardex-app


  tucardex-wa:
    image: tucardex-wa:latest
    container_name: tucardex-wa
    restart: unless-stopped
    volumes:
      - /opt/tucardex/wa-gateway/sessions:/app/sessions
    networks:
      - internal

networks:
  internal:
    driver: bridge
  proxy:
    external: true
    name: n8n_default

volumes:
  tucardex_db_data:
