<?php

return [
    'plans' => [
        'basico' => [
            'name' => 'Básico',
            'subtitle' => 'Control escolar esencial',
            'price_per_student' => 15.00,
            'public_school_price' => 10.00,
            'default_minimum_monthly' => 0.00,
            'public_school_minimum' => 2000.00,
            'popular' => false,
            'button_text' => 'Solicitar información',
            'description' => 'Ideal para escuelas públicas y colegios privados pequeños que requieren control escolar robusto sin módulos de cobranza.',
            'features' => [
                'students' => true,
                'parents' => true,
                'teachers' => true,
                'groups' => true,
                'subjects' => true,
                'academic_cycles' => true,
                'evaluation_periods' => true,
                'attendance' => true,
                'grades' => true,
                'report_cards' => true,
                'kardex' => true,
                'student_portal' => true,
                'parent_portal' => true,
                'announcements' => true,
                'academic_reports' => true,
                'school_credentials' => true,
                'school_certificates' => true,
                // Financieros
                'billing' => false,
                'payments' => false,
                'account_statements' => false,
                'debts' => false,
                'scholarships' => false,
                'receipts' => false,
                'electronic_invoicing' => false,
                'financial_reports' => false,
                // Integraciones
                'canvas' => false,
                'api' => false,
                'webhooks' => false,
                'multi_campus' => false,
                'audit' => false,
            ],
        ],
        'pro' => [
            'name' => 'Profesional',
            'subtitle' => 'Control académico, administrativo y financiero',
            'price_per_student' => 30.00,
            'default_minimum_monthly' => 0.00,
            'popular' => true,
            'badge' => 'MÁS POPULAR',
            'button_text' => 'Probar TuCardex',
            'description' => 'Control académico, administrativo y financiero en una sola plataforma. Recomendado para colegios privados.',
            'features' => [
                'students' => true,
                'parents' => true,
                'teachers' => true,
                'groups' => true,
                'subjects' => true,
                'academic_cycles' => true,
                'evaluation_periods' => true,
                'attendance' => true,
                'grades' => true,
                'report_cards' => true,
                'kardex' => true,
                'student_portal' => true,
                'parent_portal' => true,
                'announcements' => true,
                'academic_reports' => true,
                'school_credentials' => true,
                'school_certificates' => true,
                // Financieros
                'billing' => true,
                'payments' => true,
                'account_statements' => true,
                'debts' => true,
                'scholarships' => true,
                'receipts' => true,
                'electronic_invoicing' => true,
                'financial_reports' => true,
                'advanced_parent_communication' => true,
                'audit' => true,
                // Integraciones
                'canvas' => false,
                'api' => false,
                'webhooks' => false,
                'multi_campus' => false,
            ],
        ],
        'institucional' => [
            'name' => 'Integral',
            'subtitle' => 'Tu ecosistema escolar conectado',
            'price_per_student' => 45.00,
            'default_minimum_monthly' => 0.00,
            'popular' => false,
            'button_text' => 'Hablar con ventas',
            'description' => 'Ecosistema escolar completo con Canvas, automatizaciones e integraciones avanzadas para redes y colegios grandes.',
            'features' => [
                'students' => true,
                'parents' => true,
                'teachers' => true,
                'groups' => true,
                'subjects' => true,
                'academic_cycles' => true,
                'evaluation_periods' => true,
                'attendance' => true,
                'grades' => true,
                'report_cards' => true,
                'kardex' => true,
                'student_portal' => true,
                'parent_portal' => true,
                'announcements' => true,
                'academic_reports' => true,
                'school_credentials' => true,
                'school_certificates' => true,
                // Financieros
                'billing' => true,
                'payments' => true,
                'account_statements' => true,
                'debts' => true,
                'scholarships' => true,
                'receipts' => true,
                'electronic_invoicing' => true,
                'financial_reports' => true,
                'advanced_parent_communication' => true,
                'audit' => true,
                // Integraciones
                'canvas' => true,
                'api' => true,
                'webhooks' => true,
                'multi_campus' => true,
            ],
        ],
    ],
];
